"use client";
import i18next from "i18next";
import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { I18nextProvider } from "react-i18next";
import { DrawerHeader } from "@/components/drawerHeader";
import Footer from "@/components/footer";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin-ext"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className={roboto.className}>
        <div className="flex bg-transparent"></div>
        <DrawerHeader />
        <main className="min-w-screen">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
